// ─── Components barrel ────────────────────────────────────────────────────────
// Re-export all components so imports stay tidy: import { Brand } from '../components'

export { Brand } from './Brand'
export { ClientTestimonials } from './ClientTestimonials'
export { CompanyServices } from './CompanyServices'
export { ConsultationPage } from './ConsultationPage'
export { FeaturedMoneyServices } from './FeaturedMoneyServices'
export { FAQ } from './FAQ'
export { HeroBanner } from './HeroBanner'
export { IntroSplash } from './IntroSplash'
export { ProcessIllustration } from './ProcessIllustration'
export { RegistrationOffer, ServiceCatalog } from './RegistrationOfferAndCatalog'
export { RegistrationProcess } from './RegistrationProcess'
export { RegistrationDetailPage } from './RegistrationDetailPage'
export { ScrollProgress } from './ScrollProgress'
export { ServiceDirectoryPage } from './ServiceDirectoryPage'
export { ServiceIcon } from './ServiceIcon'
export { SiteFooter } from './SiteFooter'
export { SiteHeader } from './SiteHeader'
